// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    Footer: typeof import('./components/Footer.vue')['default']
    ListPosts: typeof import('./components/ListPosts.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    SelfPage: typeof import('./components/SelfPage.vue')['default']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
  }
}

export { }
