// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FriendTree: typeof import('./components/FriendTree.vue')['default']
    ListPosts: typeof import('./components/ListPosts.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    Sakura: typeof import('./components/Sakura.vue')['default']
    SelfPage: typeof import('./components/SelfPage.vue')['default']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
  }
}

export { }
