name: Build app and deploy to tencent
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # 在工作流中安装node环境（必需，这样才能在后续工作流程中运行 npm install 等指令，否则会报错）
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16 # 指定node版本
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: dist # 这是要复制到腾讯云静态服务器的文件夹名称
          REMOTE_HOST: '101.43.200.159' # 你的腾讯云公网地址
          REMOTE_USER: root # 腾讯云登录后默认为 root 用户，并且所在文件夹为 root
          TARGET: /www/wwwroot/oceanpresent.art # 打包后的 dist 文件夹将放在 /root/node-server